from pathlib import Path
from typing import List
from models.receiver import Ricevitore
import datetime

class KMLWriter:
    """Gestisce la scrittura di file KML per le coordinate dei ricevitori"""
    
    TEMPLATE_HEADER = """<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2">
  <Document>
    <name>RTK Receiver Coordinates</name>
    <description>Generated by RTK Manager on {timestamp}</description>
    <Style id="masterStyle">
      <IconStyle>
        <color>ff0000ff</color>
        <scale>1.1</scale>
        <Icon>
          <href>http://maps.google.com/mapfiles/kml/paddle/red-stars.png</href>
        </Icon>
      </IconStyle>
    </Style>
    <Style id="roverStyle">
      <IconStyle>
        <color>ff00ff00</color>
        <scale>1.1</scale>
        <Icon>
          <href>http://maps.google.com/mapfiles/kml/paddle/grn-circle.png</href>
        </Icon>
      </IconStyle>
    </Style>"""

    TEMPLATE_FOOTER = """
  </Document>
</kml>"""

    @staticmethod
    def write(receivers: List[Ricevitore], output_path: Path) -> None:
        """Scrive le coordinate dei ricevitori su file KML"""
        timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        
        with open(output_path, 'w', encoding='utf-8') as f:
            f.write(KMLWriter.TEMPLATE_HEADER.format(timestamp=timestamp))
            
            for rcv in receivers:
                if not rcv.has_coordinates():
                    continue
                    
                style = "masterStyle" if rcv.role == 'master' else "roverStyle"
                coords = rcv.get_coordinates()
                
                # Build description
                description = ""
                if rcv.role == 'master':
                    description = "Role: Master"
                else:
                    description = f"""Role: Rover
Master: {rcv.linked_master_id if rcv.linked_master_id else 'N/A'}
Solution: {rcv.sol_status if rcv.sol_status else 'N/A'}"""

                f.write(f"""
    <Placemark>
      <name>{rcv.serial_number} ({rcv.role})</name>
      <description>{description}
Lat: {coords['lat']}
Lon: {coords['lon']}
Alt: {coords['alt']}</description>
      <styleUrl>#{style}</styleUrl>
      <Point>
        <coordinates>{coords['lon']},{coords['lat']},{coords['alt']}</coordinates>
      </Point>
    </Placemark>""")
                
            f.write(KMLWriter.TEMPLATE_FOOTER)
        
        print(f"File KML creato: {output_path}")
